analytics:
  target: dev
  outputs:
    prod: 
      type: bigquery
      project: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_PROJECT_ID') }}"
      method: service-account-json
      dataset: prod
      threads: 1

      # These fields come from the service account json keyfilea
      keyfile_json:
        type: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_TYPE', 'service_account') }}"
        project_id: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_PROJECT_ID') }}"
        private_key_id: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_PRIVATE_KEY') }}"
        client_email: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_CLIENT_ID') }}"
        auth_uri: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_AUTH_URI') }}"
        token_uri: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_TOKEN_URI') }}"
        auth_provider_x509_cert_url: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_AUTH_PROVIDER_X509_CERT_URL') }}"
        client_x509_cert_url: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_CLIENT_X509_CERT_URL') }}"

    dev: 
      type: bigquery
      project: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_PROJECT_ID') }}"
      method: service-account-json
      dataset: prod
      threads: 1

      # These fields come from the service account json keyfilea
      keyfile_json:
        type: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_TYPE', 'service_account') }}"
        project_id: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_PROJECT_ID') }}"
        private_key_id: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_PRIVATE_KEY') }}"
        client_email: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_CLIENT_ID') }}"
        auth_uri: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_AUTH_URI') }}"
        token_uri: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_TOKEN_URI') }}"
        auth_provider_x509_cert_url: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_AUTH_PROVIDER_X509_CERT_URL') }}"
        client_x509_cert_url: "{{ env_var('DBT_BIGQUERY_KEYFILE_JSON_CLIENT_X509_CERT_URL') }}"